#!/bin/bash

if [ $# -lt 3 -o $# -gt 4 ]
then
    echo "ERROR – Three or four input arguments required." >&2
    exit 1
fi

infile=$1
varname=$2
value=$3
if [ $# -gt 3 ]
then
    outfile=$4
else
    outfile=$1
fi

if [ ! -e $infile ]
then
    echo "ERROR – File \"$infile\" does not exist." >&2
    exit 1
fi
if [ ! -f $infile ]
then
    echo "ERROR – \"$infile\" is not a regular file." >&2
    exit 1
fi
empty_value=false
varcheck=`grep -on "^\(\ *$varname\ *=\{1,2\}\ *\)\([^!]*[^! ]\)" $infile | wc -l`
if [ $varcheck == 0 ]
then
    varcheck=`grep -on "^\ *$varname\ *= *$" $infile | wc -l`
    if [ $varcheck == 0 ]
        then
        echo "ERROR – Variable \"$varname\" does not exist." >&2
        exit 1
    else
        empty_value=true
    fi
fi

if [ $infile -ef $outfile ]
then
    if [ $empty_value == true ]
    then
        sed -i $infile -e "s/^\(\ *$varname\ *=\{1,2\}\ *\)/\1${value//\//\\/}/g"
    else
        sed -i $infile -e "s/^\(\ *$varname\ *=\{1,2\}\ *\)[^!]*[^! ]\(.*\)/\1${value//\//\\/}\2/g"
    fi
else
    if [ $empty_value == true ]
    then
        sed -e "s/^\(\ *$varname\ *=\{1,2\}\ *\)/\1${value//\//\\/}/g" < $infile > $outfile
    else
        sed -e "s/^\(\ *$varname\ *=\{1,2\}\ *\)[^!]*[^! ]\(.*\)/\1${value//\//\\/}\2/g" < $infile > $outfile
    fi
fi

